[theme]
base = "light"
primaryColor = "#3156D3"
backgroundColor = "#F6F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#18212F"
font = "sans serif"

[server]
maxUploadSize = 25

[browser]
gatherUsageStats = false
